name: Node.js Package

on:
  release:
    types: [created]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install npx
        run: npm install -D tailwindcss
      - name: Build Tailwind CSS files
        run: npx tailwindcss -i ./src/input.css -o ./src/output.css
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: src/  # 确保路径是正确的
